export const VIEWER_JS_LIFECYCLE_DOCS = `    const lifecycleDocs = {
      AgentInitiate: {
        title: { zh: 'Agent 初始化阶段', en: 'Agent initialization phase' },
        body: {
          zh: [
          '这个时机只会在 agent 第一次真正进入工作状态时触发一次，适合做长生命周期资源的准备工作，比如启动后台服务、建立连接、预热缓存，或者把框架级能力挂进运行环境。',
          '',
          '~~~ts',
          '@AgentInitiate',
          'async boot(ctx) {',
          '  await this.indexWorkspace();',
          '  await this.startObserver();',
          '}',
          '~~~',
          '',
          '如果某个 feature 要在整个会话期间维持状态，这里通常是它最稳妥的切入点。相比 CallStart，它不会被每次用户输入重复触发。',
        ].join('\\n'),
          en: [
          'This moment fires only once when the agent truly enters its working state. It is the right place for long-lived setup such as booting background services, opening connections, warming caches, or mounting framework-level helpers.',
          '',
          '~~~ts',
          '@AgentInitiate',
          'async boot(ctx) {',
          '  await this.indexWorkspace();',
          '  await this.startObserver();',
          '}',
          '~~~',
          '',
          'If a feature needs to hold state across the whole session, this is usually the safest insertion point. Unlike CallStart, it is not repeated on every user request.',
        ].join('\\n'),
        },
      },
      AgentDestroy: {
        title: { zh: 'Agent 销毁阶段', en: 'Agent destroy phase' },
        body: { zh: [
          '这是 agent 生命周期的收尾点，用来释放外部资源、停止后台线程、断开连接，以及把调试信息或缓存安全落盘。',
          '',
          '~~~ts',
          '@AgentDestroy',
          'async cleanup() {',
          '  await this.workerPool.stop();',
          '  await this.cache.flush();',
          '}',
          '~~~',
          '',
          '如果一个 feature 在 AgentInitiate 做了重量级初始化，就应该在这里成对地清理掉。',
        ].join('\\n'),
          en: [
          'This is the closing stage of the agent lifecycle. Use it to release external resources, stop workers, close connections, and flush traces or caches safely to disk.',
          '',
          '~~~ts',
          '@AgentDestroy',
          'async cleanup() {',
          '  await this.workerPool.stop();',
          '  await this.cache.flush();',
          '}',
          '~~~',
          '',
          'If a feature performs heavyweight setup in AgentInitiate, it should usually tear that work down here.',
        ].join('\\n') },
      },
      CallStart: {
        title: { zh: 'Call 开始前', en: 'Before call start' },
        body: { zh: [
          '这个时机发生在系统提示词之后、用户输入正式写入上下文之前。它非常适合做输入重写、前置注入和会话级别的轻量整理。',
          '',
          '~~~ts',
          '@CallStart',
          'async rewriteInput(ctx) {',
          '  const raw = ctx.agent?.getUserInput() ?? ctx.input;',
          '  ctx.agent?.setUserInput(raw.trim());',
          '}',
          '~~~',
          '',
          '如果你想观察 feature 如何“提前影响”一次调用，这里通常是最有解释力的节点。',
        ].join('\\n'),
          en: [
          'This timing happens after the system prompt is ready but before the user input is committed into context. It is ideal for input rewriting, pre-injection, and lightweight call-level normalization.',
          '',
          '~~~ts',
          '@CallStart',
          'async rewriteInput(ctx) {',
          '  const raw = ctx.agent?.getUserInput() ?? ctx.input;',
          '  ctx.agent?.setUserInput(raw.trim());',
          '}',
          '~~~',
          '',
          'If you want to explain how a feature affects a call before the model sees it, this is usually the clearest node.',
        ].join('\\n') },
      },
      CallFinish: {
        title: { zh: 'Call 结束后', en: 'After call finish' },
        body: { zh: [
          '这是一次完整调用结束后的结算点。适合做摘要、记录、指标更新、落日志，而不适合决定下一轮 ReAct 要不要继续。',
          '',
          '~~~ts',
          '@CallFinish',
          'async afterCall(ctx) {',
          '  this.metrics.track(ctx.completed, ctx.steps);',
          '}',
          '~~~',
          '',
          '它更像“回合总结”，而不是流程控制点。',
        ].join('\\n'),
          en: [
          'This is the settlement point after a full call completes. It fits summarization, logging, and metrics updates, but it is not the place to decide whether the next ReAct turn should continue.',
          '',
          '~~~ts',
          '@CallFinish',
          'async afterCall(ctx) {',
          '  this.metrics.track(ctx.completed, ctx.steps);',
          '}',
          '~~~',
          '',
          'It behaves more like an end-of-call summary than a flow-control decision point.',
        ].join('\\n') },
      },
      StepStart: {
        title: { zh: 'Step 开始前', en: 'Before step start' },
        body: { zh: [
          '每轮 ReAct 循环刚开始时都会进入这里。适合做上下文补丁、提醒注入、局部状态同步。这类钩子往往会高频出现。',
          '',
          '~~~ts',
          '@StepStart',
          'async injectReminder(ctx) {',
          '  if (this.shouldRemind()) {',
          '    ctx.context.add({ role: "system", content: this.reminder });',
          '  }',
          '}',
          '~~~',
          '',
          '因为它会在每一轮执行，所以调试器里把它单独看出来很重要，否则很难解释某些系统消息为什么总会出现。',
        ].join('\\n'),
          en: [
          'Every ReAct iteration enters here right at the beginning. It is useful for context patching, reminder injection, and local state synchronization. These hooks often run at high frequency.',
          '',
          '~~~ts',
          '@StepStart',
          'async injectReminder(ctx) {',
          '  if (this.shouldRemind()) {',
          '    ctx.context.add({ role: "system", content: this.reminder });',
          '  }',
          '}',
          '~~~',
          '',
          'Because it runs every round, surfacing it clearly in the debugger is important; otherwise it is hard to explain why some system messages keep appearing.',
        ].join('\\n') },
      },
      StepFinish: {
        title: { zh: 'Step 结束决策点', en: 'Step finish decision point' },
        body: { zh: [
          '这是 ReAct 循环里最关键的控制点之一。模型和工具都跑完后，feature 可以在这里决定“继续下一轮”还是“就地结束”。',
          '',
          '~~~ts',
          '@StepFinish',
          'async decide(ctx) {',
          '  if (this.hasPendingDelegates()) {',
          '    return Decision.Approve;',
          '  }',
          '  return Decision.Continue;',
          '}',
          '~~~',
          '',
          '如果某个 feature 能把 agent 的循环强行维持住，通常就是在这里介入。它解释的是“为什么这轮已经看起来结束了，但系统还在继续跑”。',
        ].join('\\n'),
          en: [
          'This is one of the most important control points in the ReAct loop. After the model and tools finish, a feature can decide whether the loop should continue or end right away.',
          '',
          '~~~ts',
          '@StepFinish',
          'async decide(ctx) {',
          '  if (this.hasPendingDelegates()) {',
          '    return Decision.Approve;',
          '  }',
          '  return Decision.Continue;',
          '}',
          '~~~',
          '',
          'If a feature can keep the agent alive beyond what looks like a natural stopping point, it is usually intervening here.',
        ].join('\\n') },
      },
      ToolUse: {
        title: { zh: '工具执行前决策点', en: 'Before tool execution decision point' },
        body: { zh: [
          '这是另一个高价值观察位点。工具真正执行前，feature 可以在这里批准、拒绝或者放行。所有安全策略、危险操作拦截都很适合在这里实现。',
          '',
          '~~~ts',
          '@ToolUse',
          'async guard(ctx) {',
          '  if (ctx.call.name === "run_shell_command") {',
          '    return Decision.Deny;',
          '  }',
          '  return Decision.Continue;',
          '}',
          '~~~',
          '',
          '调试器里只要看清楚这里挂了谁，很多“为什么工具没执行”或者“为什么执行路径被改写”就能直接定位。',
        ].join('\\n'),
          en: [
          'This is another high-value inspection point. Before a tool actually runs, a feature can approve, deny, or pass it through. Security policy and dangerous-operation guards fit naturally here.',
          '',
          '~~~ts',
          '@ToolUse',
          'async guard(ctx) {',
          '  if (ctx.call.name === "run_shell_command") {',
          '    return Decision.Deny;',
          '  }',
          '  return Decision.Continue;',
          '}',
          '~~~',
          '',
          'As soon as you can see who is attached here, many "why did the tool not run?" questions become much easier to answer.',
        ].join('\\n') },
      },
      ToolFinished: {
        title: { zh: '工具执行后通知点', en: 'After tool finished notify point' },
        body: { zh: [
          '工具已经返回结果以后，这里会收到纯通知。适合做后处理、索引、同步外部状态、记录审计信息，但不会改变刚刚那次工具调用本身的结果。',
          '',
          '~~~ts',
          '@ToolFinished',
          'async record(ctx) {',
          '  this.auditTrail.push({',
          '    tool: ctx.toolName,',
          '    duration: ctx.duration,',
          '  });',
          '}',
          '~~~',
          '',
          '这类钩子更偏“旁路观察”和“后续整理”，所以通常适合完整展开给开发者查链路。',
        ].join('\\n'),
          en: [
          'Once a tool returns its result, this point receives a pure notification. It suits post-processing, indexing, external state sync, and audit recording, but it does not change the result of the tool call that already happened.',
          '',
          '~~~ts',
          '@ToolFinished',
          'async record(ctx) {',
          '  this.auditTrail.push({',
          '    tool: ctx.toolName,',
          '    duration: ctx.duration,',
          '  });',
          '}',
          '~~~',
          '',
          'These hooks are more about side-channel observation and cleanup, so they are usually worth showing in full detail to developers.',
        ].join('\\n') },
      },
    };
`;
